service: ${env:APPLICATION}
frameworkVersion: '4'

useDotenv: true
variablesResolutionMode: 20210326

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin
  - serverless-prune-plugin
custom:
  pythonRequirements:
    dockerizePip: false
  # prune:
  #   automatic: true
  #   number: 3
  dotenv:
    include:
      - TZ_LOCAL
  # dynamoDbTable: data_pipeline_dynamodb_table
  # dynamoDbArn: !Join
  #                 - ''
  #                 - - 'arn:aws:dynamodb:'
  #                   - !Ref 'AWS::Region'
  #                   - ':'
  #                   - !Ref 'AWS::AccountId'
  #                   - ':table/'
  #                   - ${self:custom.dynamoDbTable}
provider:
  name: aws
  runtime: ${env:PYTHON_VERSION}
  memorySize: 256
  timeout: 300
  deploymentBucket:
    name: ${env:DEPLOYMENT_BUCKET}
    maxPreviousDeploymentArtifacts: 3
  region: ${env:REGION}
  versionFunctions: true
  profile: de-class

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    # - Effect: Allow
    #   Action: 
    #     - dynamodb:*
    #   Resource:
    #     - ${self:custom.dynamoDbArn}
    # - Effect: Allow
    #   Action:
    #     - logs:*
    #   Resource: "*"

# you can define service wide environment variables here
  # environment:
  #   DYNAMO_TABLE: ${self:custom.dynamoDbTable}

# you can add packaging information here
package:
  exclude:
    - __cache__/**
    - __pycache__/**
    - node_modules/**
    - 'package.json'
    - 'package-lock.json'

functions:
  dataPipeline:
    handler: data_pipeline.run
    name: imba_data_pipeline
    description: "ETL of InstaCart"
    events:
      - s3:
          bucket: ${env:EVENT_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: data/
  
  helloapi:
    handler: helloapi.hello
    events:
      - httpApi:
          path: /
          method: get

# you can add CloudFormation resource templates here
resources:
  
  Description: InstaCart Table Creation, Data Injection, Transformation and Sinking
  
  Parameters:
    ImbaDatabaseName:
      Type: String
      Default: cfn_imba_database
    ImbaAislesTableName:
      Type: String
      Default: aisles
    ImbaAislesDataLocation:
      Type: String
      Default: s3://tgou1055-imba-sls-test-event/data/aisles/

  Resources:
    ImbaDatabase:
      Type: AWS::Glue::Database
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseInput:
          Name: !Ref ImbaDatabaseName
          Description: "Glue database for imba project"

    AislesTable:
      DependsOn: ImbaDatabase
      Type: AWS::Glue::Table
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: !Ref ImbaDatabaseName
        TableInput:
          Name: !Ref ImbaAislesTableName
          Description: "Table containing aisle data in CSV format"
          TableType: EXTERNAL_TABLE
          StorageDescriptor:
            OutputFormat: org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat
            Columns:
            - Name: aisle_id
              Type: bigint
            - Name: aisle
              Type: string
            InputFormat: org.apache.hadoop.mapred.TextInputFormat
            Location: !Ref ImbaAislesDataLocation
            SerdeInfo:
              Parameters:
                field.delim: ","
                skip.header.line.count: "1"
              SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe
 
    # pipelineDynamoDBTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: ${self:custom.dynamoDbTable}
    #     AttributeDefinitions:
    #       - AttributeName: id
    #         AttributeType: S
    #       - AttributeName: date
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: id
    #         KeyType: HASH
    #       - AttributeName: date
    #         KeyType: RANGE
    #     BillingMode: PAY_PER_REQUEST
    
